### ISSUE TITLE
Payform Name Validation Fail in Safari

### ISSUE THREAD

**Issue by jperanson** [Beanstream/beanstream-payform#56] opened 2016-10-26 20:39 UTC
### Expected behaviour:

Fill in name, email and valid credit card information into popup should allow payment to process
### Actual behaviour:

Payform client-side validation returns error "Please enter your full name"
### Browsers:

Safari Version 9.1.3 (9537.86.7.8)

**Comment by aengusbates** [comment] 2016-10-26 21:59
Hi Jonah,

What name are you inputting? We are validating on on name being a string longer than 2 chars.

Cheers, A

**Comment by jperanson** [comment] 2016-10-27 14:03
It's a proper name 7 characters in first name, 7 in last name. This was specific to Safari. The same inputs worked on Chrome.

**Comment by aengusbates** [comment] 2016-10-27 15:35
What is the name exactly?

**Comment by jperanson** [comment] 2016-10-28 18:35
It's a customer's name. It passed validation in Chrome.

**Comment by aengusbates** [comment] 2016-10-28 18:49
Hi Jonah,

I need a string to test to verify the bug. Please send on a list of special chars (non-roman alphabetic chars, punctuation, etc.) from the name, or email the name to support@beanstream.com referencing the Github issue.

Thanks, Aangus

**Comment by aengusbates** [comment] 2016-10-31 17:48
Closing issue due to insufficient detail. We can reopen issue if detail is added.

**Closed by aengusbates** 2016-10-31 17:48 UTC

**Comment by aengusbates** [comment] 2016-11-02 21:10
Unable to reproduced in Safari 10.0.1 and IE11,  IE10, Chrome (54), Firefox (48, Opera 41).

Tried to reproduce with strings "aa aa" and "aaaaaaa aaaaaaa".
